# Generated by Django 3.1.7 on 2021-12-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbdesign', '0004_auto_20211202_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbdesign.blogmodel'),
            preserve_default=False,
        ),
    ]
