# Generated by Django 3.1.7 on 2021-12-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbdesign', '0006_auto_20211202_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbdesign.blogmodel'),
        ),
    ]
